modLoader="javafml"
loaderVersion="[30,)"
[[mods]]
modId="ages_api"
version="${file.jarVersion}"
displayName="Ages API"
logoFile="ages_api.png"
authors="Yanny"

description='''
Ages API library for all Ages mods, currently there is Stone Age, but soon came Bronze Age
'''

[[dependencies.ages_api]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ages_api]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
